name: Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display placeholder message
        run: echo "Security Scan workflow placeholder for HyFuzz"
