server:
  host: 0.0.0.0
  port: 8000
  debug: false
  reload: false
  workers: 2
  worker_timeout: 60
  request_timeout: 30
  response_timeout: 60
  max_concurrent_requests: 1000
  buffer_size: 8192
  max_message_size: 1048576

transport:
  default: stdio
  stdio_enabled: true
  http_enabled: true
  http_endpoint: /mcp
  http_port: 8000
  websocket_enabled: true
  websocket_endpoint: /ws/mcp
  websocket_ping_interval: 20

telemetry:
  metrics_enabled: true
  metrics_port: 9090
  tracing_enabled: false

security:
  enable_rate_limiting: true
  max_requests_per_minute: 600
  allowed_origins:
    - "*"
