"""
Integration tests for the HyFuzz campaign coordinator.

This test suite validates the coordination engine's ability to orchestrate
distributed fuzzing campaigns across multiple protocols and targets.
"""

from __future__ import annotations

import json

from coordinator import CampaignTarget, FuzzingCoordinator


def test_coordinator_multi_protocol_campaign() -> None:
    """
    Test coordinator with multiple protocols.

    Validates that the coordinator can successfully:
    - Generate payloads for multiple protocols
    - Execute payloads across different targets
    - Collect defense verdicts and judgments
    - Aggregate campaign results
    """
    coordinator = FuzzingCoordinator(model_name="mistral-test")
    summary = coordinator.run_campaign(
        [
            CampaignTarget(name="target-coap", protocol="coap", endpoint="coap://demo"),
            CampaignTarget(name="target-modbus", protocol="modbus", endpoint="modbus://demo"),
        ]
    )

    # Validate execution count
    assert len(summary.executions) == 2, "Should execute 2 payloads (one per target)"

    # Validate feedback collection
    assert summary.feedback_history, "Feedback history should be populated"

    # Validate verdict breakdown
    breakdown = summary.verdict_breakdown()
    assert sum(breakdown.values()) == len(summary.executions), "All executions should have verdicts"

    # Validate judgment scores
    avg_score = summary.average_judgment_score()
    assert avg_score >= 0.0, "Average judgment score should be non-negative"
    assert avg_score <= 1.0, "Average judgment score should not exceed 1.0"

    # Validate individual execution details
    for detail in summary.executions:
        # Check payload generation
        assert detail.payload.startswith("mistral-test"), "Payload should be generated by test model"

        # Check execution correlation
        assert detail.execution.payload_id == detail.request_id, "Payload IDs should match"
        assert detail.execution.output, "Execution should produce output"

        # Check LLM judgment
        assert detail.judgment.score >= 0.0, "Judgment score should be non-negative"
        assert detail.judgment.score <= 1.0, "Judgment score should not exceed 1.0"

        # Check defense analysis
        assert detail.defense is not None, "Defense analysis should be present"
        verdict = detail.defense.verdict
        assert verdict in {"monitor", "investigate", "block", "escalate"}, f"Invalid verdict: {verdict}"

        # Check protocol-specific parameters
        template = json.loads(detail.request_parameters["payload_template"])
        assert template["target"] == detail.target.endpoint, "Target endpoint should match"

        if detail.target.protocol == "coap":
            assert template["method"] == "GET", "CoAP should use GET method"
            assert template["path"].startswith("/"), "CoAP path should start with /"
            assert "confirmable" in template, "CoAP should have confirmable flag"

        if detail.target.protocol == "modbus":
            assert int(template["function_code"]) == 3, "Modbus should use function code 3 (read)"
            assert int(template["count"]) == 1, "Modbus should read 1 register"
            assert "address" in template, "Modbus should have address field"


def test_coordinator_coap_only() -> None:
    """Test coordinator with only CoAP targets."""
    coordinator = FuzzingCoordinator(model_name="test")

    summary = coordinator.run_campaign([
        CampaignTarget(name="coap-1", protocol="coap", endpoint="coap://device1:5683"),
        CampaignTarget(name="coap-2", protocol="coap", endpoint="coap://device2:5683"),
    ])

    assert len(summary.executions) == 2
    for detail in summary.executions:
        assert detail.target.protocol == "coap"


def test_coordinator_modbus_only() -> None:
    """Test coordinator with only Modbus targets."""
    coordinator = FuzzingCoordinator(model_name="test")

    summary = coordinator.run_campaign([
        CampaignTarget(name="modbus-plc", protocol="modbus", endpoint="modbus://plc:502"),
    ])

    assert len(summary.executions) == 1
    assert summary.executions[0].target.protocol == "modbus"


def test_coordinator_empty_targets() -> None:
    """Test coordinator behavior with empty target list."""
    coordinator = FuzzingCoordinator(model_name="test")

    summary = coordinator.run_campaign([])

    assert len(summary.executions) == 0
    assert summary.average_judgment_score() == 0.0
    assert summary.verdict_breakdown() == {}


def test_coordinator_summary_export() -> None:
    """Test summary export to dictionary format."""
    coordinator = FuzzingCoordinator(model_name="test")

    summary = coordinator.run_campaign([
        CampaignTarget(name="test", protocol="coap", endpoint="coap://test"),
    ])

    # Export to dictionary
    summary_dict = summary.to_dict()

    # Validate dictionary structure
    assert "executions" in summary_dict
    assert "feedback" in summary_dict
    assert "verdict_breakdown" in summary_dict
    assert "average_judgment" in summary_dict

    # Validate types
    assert isinstance(summary_dict["executions"], list)
    assert isinstance(summary_dict["feedback"], list)
    assert isinstance(summary_dict["verdict_breakdown"], dict)
    assert isinstance(summary_dict["average_judgment"], (int, float))


if __name__ == "__main__":  # pragma: no cover - smoke run
    import pytest

    pytest.main([__file__, "-v"])
